#pragma once

#include <glad/glad.h>

#define EF_INVALID

#define EF_BLEND				GL_BLEND
#define EF_FUNC_ADD				GL_FUNC_ADD
#define EF_SRC_ALPHA			GL_SRC_ALPHA
#define EF_ONE_MINUS_SRC_ALPHA	GL_ONE_MINUS_SRC_ALPHA
#define EF_ONE_MINUS_SRC_COLOR	GL_ONE_MINUS_SRC_COLOR
#define EF_SRC_COLOR			GL_SRC_COLOR
#define EF_ZERO				GL_ZERO
#define EF_ONE				GL_ONE
#define EF_CULL_FACE			GL_CULL_FACE
#define EF_DEPTH_TEST			GL_DEPTH_TEST
#define EF_SCISSOR_TEST		GL_SCISSOR_TEST
#define EF_COLOR_BIT			GL_COLOR_BUFFER_BIT
#define EF_DEPTH_BIT			GL_DEPTH_BUFFER_BIT
// OPENGL VERSION SPECIFIC RENDER STATES
#if !defined(USE_OPENGLES)
#define EF_FRONT_AND_BACK		GL_FRONT_AND_BACK
#define EF_FILL				GL_FILL
#else
#define EF_FRONT_AND_BACK		EF_INVALID
#define EF_FILL				EF_INVALID
#endif
// Framebuffer
#define EF_DRAW_FBO	GL_DRAW_FRAMEBUFFER
#define EF_READ_FBO	GL_READ_FRAMEBUFFER
#define EF_FBO		GL_FRAMEBUFFER
#define EF_RBO		GL_RENDERBUFFER
#define EF_COLOR_ATTACHMENT0 GL_COLOR_ATTACHMENT0
// Texture Locators
#define EF_TEXTURE_2D	GL_TEXTURE_2D
#define EF_TEXTURE_3D	GL_TEXTURE_3D
#define EF_TEXTURE0		GL_TEXTURE0
#define EF_TEXTURE1		GL_TEXTURE1
#define EF_TEXTURE2		GL_TEXTURE2
#define EF_TEXTURE3		GL_TEXTURE3
#define EF_TEXTURE4		GL_TEXTURE4
#define EF_TEXTURE5		GL_TEXTURE5
#define EF_TEXTURE6		GL_TEXTURE6
#define EF_TEXTURE7		GL_TEXTURE7
#define EF_TEXTURE8		GL_TEXTURE8
#define EF_TEXTURE9		GL_TEXTURE9
#define EF_TEXTURE10	GL_TEXTURE10
#define EF_TEXTURE11	GL_TEXTURE11
#define EF_TEXTURE12	GL_TEXTURE12
#define EF_TEXTURE13	GL_TEXTURE13
#define EF_TEXTURE14	GL_TEXTURE14
#define EF_TEXTURE15	GL_TEXTURE15
#define EF_TEXTURE16	GL_TEXTURE16
#define EF_TEXTURE17	GL_TEXTURE17
#define EF_TEXTURE18	GL_TEXTURE18
#define EF_TEXTURE19	GL_TEXTURE19
#define EF_TEXTURE20	GL_TEXTURE20
#define EF_TEXTURE21	GL_TEXTURE21
#define EF_TEXTURE22	GL_TEXTURE22
#define EF_TEXTURE23	GL_TEXTURE23
#define EF_TEXTURE24	GL_TEXTURE24
#define EF_TEXTURE25	GL_TEXTURE25
#define EF_TEXTURE26	GL_TEXTURE26
#define EF_TEXTURE27	GL_TEXTURE27
#define EF_TEXTURE28	GL_TEXTURE28
#define EF_TEXTURE29	GL_TEXTURE29
#define EF_TEXTURE30	GL_TEXTURE30
#define EF_TEXTURE31	GL_TEXTURE31
// Draw Mode
#define EF_STATIC_DRAW		GL_STATIC_DRAW
#define EF_STREAM_DRAW		GL_STREAM_DRAW
#define EF_DYNAMIC_DRAW		GL_DYNAMIC_DRAW
#define EF_TRIANGLES		GL_TRIANGLES
#define EF_QUADS			GL_QUADS
#define EF_LINES			GL_LINES
#define EF_POINTS			GL_POINTS
// Data Types
#define EF_BYTE    GL_BYTE
#define EF_UBYTE   GL_UNSIGNED_BYTE
#define EF_USHORT  GL_UNSIGNED_SHORT
#define EF_UINT    GL_UNSIGNED_INT
#define EF_INT     GL_INT
#define EF_FLOAT   GL_FLOAT
#define EF_DOUBLE  GL_DOUBLE
#define EF_FVEC2		GL_FLOAT_VEC2
#define EF_FVEC3		GL_FLOAT_VEC3
#define EF_FVEC4		GL_FLOAT_VEC4
#define EF_FMAT4		GL_FLOAT_MAT4
#define EF_SAMPLER2D	GL_SAMPLER_2D
//... keep adding, not good but eh
// Texture Types
#define EF_RGBA   GL_RGBA
#define EF_RGBA8  GL_RGBA8
#define EF_R8     GL_R8
#define EF_R16    GL_R16
#define EF_RGB    GL_RGB
#define EF_RGB8   GL_RGB8
#define EF_TYPE_DEPTH GL_DEPTH_ATTACHMENT
#define EF_DEPTH16	GL_DEPTH_COMPONENT16
#define EF_DEPTH24	GL_DEPTH_COMPONENT24
#define EF_DEPTH32	GL_DEPTH_COMPONENT32
#define EF_DEPTH32F	GL_DEPTH_COMPONENT32F
// Texture Parameters
#define EF_MIP_MAX_LEVEL      GL_TEXTURE_MAX_LEVEL
#define EF_MIP_MIN_LEVEL      GL_TEXTURE_BASE_LEVEL
#define EF_MIN_FILTER		    GL_TEXTURE_MIN_FILTER
#define EF_MAG_FILTER		    GL_TEXTURE_MAG_FILTER
#define EF_WRAP_S		        GL_TEXTURE_WRAP_S
#define EF_WRAP_T			    GL_TEXTURE_WRAP_T
#define EF_BORDER_COLOR       GL_TEXTURE_BORDER_COLOR
#define EF_NEAREST            GL_NEAREST
#define EF_LINEAR             GL_LINEAR
#define EF_NEAREST_NEAREST    GL_NEAREST_MIPMAP_NEAREST
#define EF_LINEAR_NEAREST     GL_LINEAR_MIPMAP_NEAREST
#define EF_NEAREST_LINEAR     GL_NEAREST_MIPMAP_LINEAR
#define EF_LINEAR_LINEAR      GL_LINEAR_MIPMAP_LINEAR
#define EF_CLAMP              GL_CLAMP_TO_EDGE
#define EF_MIRROR             GL_MIRRORED_REPEAT
#define EF_REPEAT             GL_REPEAT
// Shaders
#define EF_VERTEX_SHADER      GL_VERTEX_SHADER
#define EF_FRAGMENT_SHADER    GL_FRAGMENT_SHADER
#define EF_GEOMETRY_SHADER	GL_GEOMETRY_SHADER

